# Introduction

Many species are under significant pressure from human development and resource use. These effects are coupled with existing pressures from climate change and natural disturbances. Collectively, these pressures can compound and interact to have cumulative effects on many species and ecosystems. Attempts have been made to quantify, map, and model cumulative effects across a landscape or region of interest to understand current conditions, high vs low-risk areas, and potential future conditions under different (hypothetical) development scenarios. However, the applicability of many analytical tools and frameworks is often constrained to specific geographies, study systems or regulatory requirements. In addition, many tools or frameworks are either too specific or over-generalized to be broadly transferable, causing researchers to develop their own models from scratch and duplicate efforts when undertaking cumulative effects (CE) assessments. In addition, most CE modelling tools merely rank the severity of local stressors using an additive or multiplicative scoring system based on the co-occurrence of multiple stressors (e.g., [@halpern2013assumptions]). While this provides a useful index of local stressor magnitude, it provides limited insight into *how* ecological values will respond to stressor reduction, which requires predictive stressor-response functions.

The CEMPRA tool leverages (and automates) common data processing and analytical pathways reoccurring across numerous cumulative effects assessments. The development team behind the CEMPRA tool also recognizes that many cumulative effects assessments are collaborative and highly iterative. As such, an interactive web application was developed alongside an analytical R-package to facilitate the development of cumulative effects assessments in a workshop-like setting. The CEMPRA R-Shiny web application facilitates the inclusion and leadership of land stewards and decision-makers in the assessment and analytical process by working around a centralized interactive choropleth (heat) map. Key locations are represented by polygons on the map linked to interactive stressors and stressor-response relationships. Numerous interactive visualizations and summary tables are included within the tool to facilitate rapid "what if" scenario assessments. The CEMPRA tool does not include all possible options for advanced analytics. However, it can be a useful starting point to engage different user groups and work towards a shared understanding of key drivers, processes and opportunities for a target study system and region of interest.

The inspiration for the CEMPRA tool originated from many case studies centred around aquatic species-at-risk in Canada and is based on the Alberta Cumulative Effects model ([@macpherson2020alberta], [@macpherson2023prioritizing]). However, the underlying framework is not explicitly bound to aquatic or terrestrial ecosystems. Aquatic ecosystems have remained the primary focus of the CEMPRA tool's development in response to numerous contemporary priorities, including a) practical guidance for watershed management, b) recent amendments to the Fisheries Act prompting the consideration of cumulative effects (past and current), c) empowering practitioners with tools and resources to initialize collaborative cumulative effects assessments.

Key components of the CEMPRA include a focal study system (e.g., a target population), a focal area of interest (i.e., a target region with defined sub-areas, locations, or spatial units with different stressor levels), key stressors of interest (e.g., stream temperature, sedimentation, habitat loss), stressor-response functions linking key stressors to the focal population or species of interest, estimates of stressor magnitude levels across the target region of interest (e.g., current stressor conditions in the different spatial units), and different assessment endpoints (i.e., either the single-stage Joe model output or the life cycle model output) for data-rich and data-limited systems, and scenarios to represent in the model (i.e., future "what if" possibilities or alternative management scenarios).

**Core Components of the CEMPRA Tool:**

Unlike most CE models that score (weight) multiple stressors to generate an index of overlapping stressor levels at a given location ([@halpern2013assumptions]), CEMPRA goes one step further to estimate the impact of a given stressor level on a target ecological response in any given spatial unit, based on local stressor levels. This "Joe" model structure requires the following components:

**Study System**: In all applications of the CEMPRA tool, users should frame their assessment around a focal study system. Previous (and ongoing) applications of the Joe/CEMPRA model have included Athabasca Rainbow Trout ([@sullivan2017adaptive]), Bull trout in Alberta ([@macpherson2023prioritizing]), Chinook Salmon in the Nicola Basin ([@pearsall2022nicola]) and the Plains Sucker in Southeastern Alberta (L. Jarvis, personal communication, February 23, 2023). On occasion, the term "study system" is used in conjunction with "cumulative effects" to describe a project or development within the Environmental Impact Assessment (EIA) literature. However, the CEMPRA tool uses specific user-defined valued ecosystem components as the study system. Usually, these are target populations or species, but occasionally they can be interpreted as broader entities with basic applications of CEMPRA where stressors are linked to "aquatic ecosystems". If broader interpretations describe a study system, care should be taken to ensure that the stressor response functions are still interpretable and biologically relevant. For example, suppose CEMPRA is used for a multi-species assessment. In that case, creating species-specific stressor response curves and running scenarios for each species will likely be necessary.

**Stressors**: Stressors and stressor-response functions are a core part of the CEMPRA tool. For the purposes of this tool, "stressors" can be defined broadly as "any environmental variable (e.g., temperature, sediment, predation, competition) that can induce a biological response (positive or negative)" ([@rosenfeld2024determinants]; [@jarvis2023process]). Stressors can include any user-defined environmental variable (or driver) that prevents the target species (or ecosystem component) from reaching a fully realized maximum system capacity that would presumably be possible without any harmful impacts. Stressors and stressor-response functions are described further in the next section.

**Stressor-Response Function:** Stressor-response functions link stressors to the local abundance of the target species or value. The key defining components of stressor-response functions within the CEMPRA tools are that they represent quantitative linkages between raw stressor values and the predicted biological response. Stressor-response functions are equivalent to dose-response curves. They can also be interpreted as habitat suitability curves; however, the default assumption in most cumulative effects assessments is that target locations under evaluation have the capacity to support the study species in the absence of extreme stressor levels. Stressors and stressor-response functions are described further in the next section.

**Locations:** The terms "locations", "study areas", "spatial units", "polygons", and/or "assessment units" are used interchangeably to describe discrete user-defined locations in the study region. Locations are represented in the CEMPRA tool as spatial polygons; linear features like stream reaches can also be represented as narrow polygons. Spatial units can be user-defined based on environmental heterogeneity and an area's capacity to support the target species. Ideally, location breaks are chosen such that stressor values are largely homogenous within a spatial unit. Location breaks can also be defined to represent known (or suspected) subpopulations if they match management objectives or variations in stressor levels. In most cumulative effects assessments of aquatic ecosystems, location breaks will almost always be generated based on watersheds or subbasin boundaries since these natural geographic breaks often drive differences in key stressor values across the landscape.

**Assessment Endpoints**: The ability to effectively link environmental stressors to a focal species using stressor-response functions is a core underlying function of the CEMPRA tool that differentiates it from many other cumulative effects models. Stressor-response functions allow stressor levels in a specific polygon to be used to predict the expected ecological response (system capacity). The CEMPRA tool provides two major workflows and assessment endpoints suitable for data-poor and data-rich systems. Stressor-response functions can be combined with stressor magnitudes in a polygon to predict local habitat capacity based on each stressor level, and the product of predicted habitat capacities for each stressor is used to generate an aggregate cumulative effect of all stressors on adult carrying capacity (the classical single-stage 'Joe Model'); alternatively, stressors can be run through an integrated life cycle model where stressor-response functions are linked to vital rates (e.g., survivorship, capacity) for discrete life-history stages. The simplified roll-up ('Joe Model') is useful for data-limited species, but it also serves as a convenient framework for a rapid first-pass assessment to generate heatmaps of stressor severity. The integrated life cycle model has special utility for more data-rich systems where it's possible to weight and understand stressors through the lens of a demographic stage-structured population framework. This can be especially important where some stressors will have disproportionate impacts on a specific life-history bottleneck and is appropriate for well-studies species with sufficient data to parameterize a population model.

**Scenarios:** Scenarios represent unique user-defined management or recovery interventions (or the absence of action in a reference scenario) that aid the comparison of the outcome of different management actions. Scenarios (or scenario profiles) can include a combination of changes in one or more stressors at one or more locations to represent a hypothetical management action (or inaction). Scenarios can be implemented as changes to the stressor values (across locations) and/or changes to the stressor-response relationships, changing the underlying assumption of impact pathways (e.g., for a sensitivity analysis if there is uncertainty in stressor magnitudes or stress-or response functions).

The purpose of this user guide is to introduce these concepts in further detail with examples that demonstrate how they can be used to implement cumulative effects assessments in the CEMPRA framework. The following sections include setup instructions, a quick start guide, an overview of data inputs, and example cases. The intent is also to highlight the flexibility of the CEMPRA tool as a a generalizable and easy-to-use cumulative effects modelling framework that is adaptable to many different systems and/or species.
