# Concluding Remarks {#concluding-remarks}

## Benefits and Limitations {#11_conclusions-benefits-and-limitations}

The CEMPRA tool has the flexibility to perform cumulative effects assessments for both data-rich and data-poor species, allowing for the analysis of a range of study systems, including species-at-risk. Various assessment endpoints are available for different use cases. With only four generic input datasets, onboarding new users is intended to be relatively simple.

The Joe Modelling component of the CEMPRA tool is a generic assessment framework widely applicable to data-rich and data-limited species. The Joe Model acts as a simplified stressor roll-up framework for watershed assessments. Stressors can be added and manipulated in near real-time in a workshop-like setting. Proven use cases on numerous study systems show how it can be a critical asset to facilitate a shared understanding of watershed stewardship and high-level strategy development for watershed planning.

The life cycle modelling component of the CEMPRA tool offers the ability to link stressors to key vital rates in a demographic modelling framework. User groups and practitioners can solicit the life cycle models to help develop high-level goals for restoration and recovery programs ([@roni2018review]). Life cycle models are useful to identify key demographic bottlenecks and the sensitivity of those bottlenecks to the range of stressor values observed on the landscape (or projected through scenario simulation).

The CEMPRA framework should be considered a simple approach to cumulative effects assessments. It provides the greatest utility for large-scale planning activities at the intersection between different user groups and stakeholders. The intent of the CEMPRA tool is to provide a working framework for both data-rich and data-limited species with alternative assessment endpoints. Stressor-response relationships are the underlying theme of the CEMPRA tool. Our hope is that the CEMPRA will support the development of a collaborative user community, reducing duplicated efforts in the development of stressor variables, species profiles and assessment frameworks.
