---
title: "Socio-economic Evaluation of Restoration Actions"
format: html
---

[Download the SE Module](assets/Restoration_Action.pdf)


{{< video https://www.youtube.com/watch?v=kkebo1rybp4 >}}

The Joe Model and Life Cycle Model components of the CEMPRA tool primarily focus on status, condition, and relative risk rating(s) among assessment units, scenarios, and stressors, providing insights when formulating management priorities for a watershed or study system. However, First Nations, industry, governing bodies, and conservation initiatives/collaboratives seeking to mitigate stressors within a framework of potential restoration actions need to understand the comparative costs of competing management interventions. To address this need, the socio-economic component of the CEMPRA tool generates an overview of the costs and effectiveness of user-defined management strategies associated with stressor reduction. The socio-economic component attempts to provide a high-level cost-benefit analysis of restoration alternatives, and is designed to facilitate decision-making by quantifying the economic implications of competing restoration strategies.

[Download](assets/Restoration_Action.pdf) the manual for the socioeconomic module (linked below).

![Overview of the linked relationships underlying the socio-economic evaluation of restoration actions in the CEMPRA tool showing a.) reduction in stressor level from a hypothetical management action, following a pre-defined stressor-response function; b.) cost associated with the management action/intervention (intervention-cost function); and c.) the resulting cost-benefit analysis that provides insights into relative trade-offs between restoration actions, stressor reduction, and associated cost.](images/se_module.png){fig-align="center"}


[Download Restoration Action Socio-Economic Module User Guide Here](assets/Restoration_Action.pdf)



